[package]
name = "tetsy-kvdb"
version = "0.9.0"
authors = ["Parity Technologies <admin@parity.io>"]
repository = "https://github.com/tetcoin/tetsy-common"
description = "Generic key-value trait"
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
smallvec = "1.0.0"
tetsy-util-mem = { path = "../tetsy-util-mem", version = "0.9", default-features = false }
