[package]
name = "tetsy-kvdb-memorydb"
version = "0.9.0"
authors = ["Parity Technologies <admin@parity.io>"]
repository = "https://github.com/tetcoin/tetsy-common"
description = "A key-value in-memory database that implements the  `KeyValueDB` trait"
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
tetsy-util-mem = { path = "../tetsy-util-mem", version = "0.9", default-features = false, features = ["std"] }
parking_lot = "0.11.1"
tetsy-kvdb = { version = "0.9", path = "../tetsy-kvdb" }

[dev-dependencies]
tetsy-kvdb-shared-tests = { path = "../tetsy-kvdb-shared-tests", version = "0.7" }

[features]
default = []
